name: CD to Production (on main)
on:
  push:
    branches: [main]

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure prod RG
        run: az group create -n ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -l australiaeast

      - name: Upsert customer_service
        run: |
          TAG=${GITHUB_SHA}
          az container show -g ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -n prod-customer >/dev/null 2>&1 && \
            az container delete -y -g ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -n prod-customer
          az container create -g ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -n prod-customer \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:$TAG \
            --ports 8001 --ip-address Public --cpu 1 --memory 1

      - name: Upsert order_service
        run: |
          TAG=${GITHUB_SHA}
          az container show -g ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -n prod-order >/dev/null 2>&1 && \
            az container delete -y -g ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -n prod-order
          az container create -g ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -n prod-order \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/order_service:$TAG \
            --ports 8002 --ip-address Public --cpu 1 --memory 1

      - name: Upsert product_service
        run: |
          TAG=${GITHUB_SHA}
          az container show -g ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -n prod-product >/dev/null 2>&1 && \
            az container delete -y -g ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -n prod-product
          az container create -g ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -n prod-product \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/product_service:$TAG \
            --ports 8003 --ip-address Public --cpu 1 --memory 1

      - name: Upsert frontend
        run: |
          TAG=${GITHUB_SHA}
          az container show -g ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -n prod-frontend >/dev/null 2>&1 && \
            az container delete -y -g ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -n prod-frontend
          az container create -g ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -n prod-frontend \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/frontend:$TAG \
            --ports 80 --ip-address Public --cpu 1 --memory 1

      - name: Output prod URL
        run: |
          IP=$(az container show -g ${{ secrets.AZURE_RESOURCE_GROUP_PROD }} -n prod-frontend --query ipAddress.ip -o tsv)
          echo "Prod URL: http://$IP"
