name: CI (testing)
on:
  push:
    branches: [testing]

jobs:
  build_test_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate secrets
        run: |
          test -n "${{ secrets.ACR_NAME }}" || { echo "ACR_NAME secret missing"; exit 1; }
          test -n "${{ secrets.ACR_LOGIN_SERVER }}" || { echo "ACR_LOGIN_SERVER secret missing"; exit 1; }

      - name: ACR login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build images
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }} ./frontend
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:${{ github.sha }} ./backend/customer_service
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/order_service:${{ github.sha }}    ./backend/order_service
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/product_service:${{ github.sha }}  ./backend/product_service

      - name: Push images
        if: ${{ success() }}
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/order_service:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/product_service:${{ github.sha }}
