name: CI (testing)
on:
  push:
    branches: [testing]

jobs:
  build_test_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      # Optional: run any npm tests if present
      - name: Frontend install & test (if present)
        run: |
          if [ -f frontend/package.json ]; then
            npm ci --prefix frontend
            npm test --prefix frontend --if-present
          fi

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build images
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }} ./frontend
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:${{ github.sha }} ./backend/customer_service
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/order_service:${{ github.sha }}    ./backend/order_service
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/product_service:${{ github.sha }}  ./backend/product_service

      - name: Push images ONLY if previous steps succeeded
        if: ${{ success() }}
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer_service:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/order_service:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/product_service:${{ github.sha }}
